fixed dynamic shape in transpose conv
VeriSilicon/tflite-vx-delegate pull request #144
Opened 2022-10-06 08:41 UTC by chxin66

Signed-off-by: Chen Xin <jack.chen@verisilicon.com>

2022-10-08 07:04 UTC, sunshinemyson requested changes

2022-10-08 07:04 UTC, sunshinemyson commented on op_map.cc
> +      tim::vx::TensorSpec output_spec(tim::vx::DataType::INT32,
output always int32?

2022-10-08 07:04 UTC, sunshinemyson commented on op_map.cc
> +    // output_shape[1]=1; //按照pack的输出output_shape[1]是8，hack为1后正确
Fix this ?

2022-10-08 07:04 UTC, sunshinemyson commented on op_map.cc
> +      tim::vx::TensorSpec output_spec(tim::vx::DataType::INT32,
always int32?

2022-10-08 07:04 UTC, sunshinemyson commented on op_map.cc
> +      tim::vx::TensorSpec output_spec(tim::vx::DataType::INT32,
int32?

2022-10-12 06:28 UTC, sunshinemyson requested changes

2022-10-12 06:28 UTC, sunshinemyson commented on op_map.cc
> +std::vector<uint8_t> read_output_data(std::shared_ptr<tim::vx::Tensor> tensor) {
bool read_data(const .. & tensor, std::vector<uint8_t>& out_data)

2022-10-12 08:31 UTC, chxin66 commented on op_map.cc
> +std::vector<uint8_t> read_output_data(std::shared_ptr<tim::vx::Tensor> tensor) {
done

2022-11-02 03:18 UTC, closed without merging