build tim-vx and tflite as module in cmake
VeriSilicon/tflite-vx-delegate pull request #33
Opened 2021-11-24 08:42 UTC by liyuenan2333

Signed-off-by: yuenan.li <yuenan.li@verisilicon.com>

2021-11-24 09:07 UTC, sunshinemyson commented on CMakeLists.txt
> +find_package(tensorflow)
add required.

2021-11-24 09:08 UTC, sunshinemyson requested changes

2021-11-24 09:23 UTC, liyuenan2333 commented on CMakeLists.txt
> +find_package(tensorflow)
done

2021-11-24 09:24 UTC, liyuenan2333 commented on CMakeLists.txt
> +find_package(tim-vx REQUIRED)
It's not available in this project.

2021-11-25 06:45 UTC, sunshinemyson approved these changes

2021-11-25 06:45 UTC, merged